### ISSUE TITLE
打开视频会闪几下窗口才播放

### ISSUE THREAD

**Issue by izen000** [NeilTohno/mpv_config2#1]
你好，我用了你的配置想问问打开视频为什么会闪几下窗口才正常播放？就是自动打开关闭 mpv.exe 2~3次才正常播放。谢谢

**Comment by NeilTohno** [comment]
> 你好，我用了你的配置想问问打开视频为什么会闪几下窗口才正常播放？就是自动打开关闭 mpv.exe 2~3次才正常播放。谢谢

嗯，把你电脑的配置发出来（包括显示器分辨率，刷新率），
说明一下要播放的文件夹下视频（多个？）的分辨率和格式（包括是否为HDR），
最后按打开播放器按键盘  i，再按字母区上面的数字 1，
截图给我哈，如果能打包附上 日志.zip 也行

**Comment by izen000** [comment]
不好意思现在才回复。
我的配置是R5-6600H+3050，分辨率是2560*1440，165hz
播放文件夹下就一个或者几个视频都一样，普通的1080P，SDR视频
[mpv.log](https://github.com/user-attachments/files/16707252/mpv.log) ⬅️日志是这样上传么？
<img src="https://tu.wnflb2023.com/i/2024/08/22/155045.png" alt="QQ20240822-154805" />

**Comment by NeilTohno** [comment]
> 不好意思现在才回复。 我的配置是R5-6600H+3050，分辨率是2560*1440，165hz 播放文件夹下就一个或者几个视频都一样，普通的1080P，SDR视频 [mpv.log](https://github.com/user-attachments/files/16707252/mpv.log) ⬅️日志是这样上传么？ ![QQ20240822-154805](https://camo.githubusercontent.com/5effb61b2e3d3393564d5d16c4f755e6987348b318d1cba28ae7e4e5eba88e07/68747470733a2f2f74752e776e666c62323032332e636f6d2f692f323032342f30382f32322f3135353034352e706e67)

在这里我说了关于显示器刷新率和视频帧率 的问题，
https://github.com/NeilTohno/mpv_config

其实显示器支持 120Hz 的话，开这个就行，各种帧率的视频都流畅，当某个需要 165Hz 的时候再开回来
高刷新率下开着 interpolation 特别消耗资源
log 里面一堆 **interpolation queue underrun**


请尝试下面的设置：
1. 显示器使用 120Hz，然后把配置文件里面 # A/V sync  那段注释掉
2. N 卡某些版本驱动对 vulkan api 支持不怎么好，可以把配置里面的 api 改成 d3d11，在配置文件 [low]  [SD]  [HD30] [HD60]  [FHD] [2K30] [4K30] [UHD60] 的 profile=high_quality3 改成 profile=high_quality 就行

其余可以看看这里 
https://vcb-s.com/archives/7594

以上。

**Comment by izen000** [comment]
好的谢谢
